syntax = "proto3";

option java_package = "com.coolApps.MultipleAlarmClock.Data.dataStore";
option java_multiple_files = true;

message Settings {
  bool is_first_launch = 1;
  bool all_permissions_granted = 2;
  bool first_alarm_set = 3;
  bool first_alarm_notification_received = 4;
  bool should_we_show_feedback_card = 5;
//  InAppReviewState should_we_show_in_app_review = 6;
  bool should_we_show_in_app_review = 6;
  int64 install_epoch_time_ms = 7; // set once, at onboarding completion
  int64 last_review_attempted_at = 8;

}

//enum InAppReviewState {
//    NOT_ELIGIBLE = 0;
//    ELIGIBLE = 1;
//    CONSUMED = 2;
//}
