name: Android Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version number
        id: version
        run: |
          latest_tag=$(git tag -l "v[0-9]*" | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            echo "next_version=1" >> $GITHUB_OUTPUT
          else
            current_version=${latest_tag#v}
            next_version=$((current_version + 1))
            echo "next_version=$next_version" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

      - name: Update Gradle Properties
        run: |
          cat << EOF > signing.properties
          STORE_FILE=release.keystore
          STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF
          mv signing.properties app/signing.properties

      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --warning-mode all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: v${{ steps.version.outputs.next_version }}
          name: Release v${{ steps.version.outputs.next_version }}
          body: |
            Automated release of the latest APK build for the main branch.
            Build number: ${{ steps.version.outputs.next_version }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false