name: Android Build & Release

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions: read-all
        permissions: write-all
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk
          tag_name: v${{ github.run_number }}  # or your preferred versioning
          name: Release v${{ github.run_number }}
          body: |
            Automated release of the latest APK build for the main branch.
            Build number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
        