name: Android Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ... (previous steps remain the same) ...

      - name: Install zipalign
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign
          zipalign -v

      - name: Verify APK location and create output directory
        run: |
          ls -la app/build/outputs/apk/release/
          mkdir -p app/build/outputs/apk/release/aligned

      - name: Align APK with zipalign
        run: |
          # Add force flag to overwrite if file exists
          zipalign -f -v -p 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/aligned/app-release-unsigned-aligned.apk
          
          # Verify alignment
          zipalign -c -v 4 app/build/outputs/apk/release/aligned/app-release-unsigned-aligned.apk || {
            echo "Alignment verification failed"
            exit 1
          }
          
          # List the resulting file
          ls -la app/build/outputs/apk/release/aligned/

      - name: Sign aligned APK
        run: |
          apksigner sign --ks app/release.keystore \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            app/build/outputs/apk/release/aligned/app-release-unsigned-aligned.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/aligned/app-release-unsigned-aligned.apk
          tag_name: v${{ steps.version.outputs.next_version }}
          name: Release v${{ steps.version.outputs.next_version }}
          body: |
            Automated release of the latest APK build for the main branch.
            Build number: ${{ steps.version.outputs.next_version }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false